# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bBlCPgY27TE9quVtcTiiTv-DJoNp2t5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import warnings
warnings.filterwarnings('ignore')

# 1. CARGAR Y EXPLORAR LOS DATOS
print("=== CARGANDO DATOS ===")
df = pd.read_csv('sample_data/insurance.csv')
print(f"Dimensiones del dataset: {df.shape}")
print(f"\nPrimeras 5 filas:")
print(df.head())
print(f"\nInformación del dataset:")
print(df.info())
print(f"\nEstadísticas descriptivas:")
print(df.describe())

# 2. ANÁLISIS EXPLORATORIO INICIAL
print("\n=== ANÁLISIS EXPLORATORIO ===")
print(f"\nValores nulos por columna:")
print(df.isnull().sum())
print(f"\nDistribución de variables categóricas:")
print(f"Sexo: {df['sex'].value_counts()}")
print(f"Fumador: {df['smoker'].value_counts()}")
print(f"Región: {df['region'].value_counts()}")

# Visualización de distribución de la variable objetivo
plt.figure(figsize=(10, 6))
plt.subplot(1, 2, 1)
sns.histplot(df['charges'], kde=True)
plt.title('Distribución de Charges')
plt.subplot(1, 2, 2)
sns.histplot(np.log1p(df['charges']), kde=True)
plt.title('Distribución de log(Charges)')
plt.tight_layout()
plt.show()

# 3. PREPROCESAMIENTO DE DATOS
print("\n=== PREPROCESAMIENTO ===")

# Codificación de variables categóricas
label_encoders = {}
categorical_columns = ['sex', 'smoker', 'region']

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le
    print(f"{col} codificado: {dict(zip(le.classes_, le.transform(le.classes_)))}")

# Separar características y variable objetivo
X = df.drop('charges', axis=1)
y = df['charges']

print(f"\nCaracterísticas después del preprocesamiento:")
print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

# 4. TRANSFORMACIÓN DE LA VARIABLE OBJETIVO (opcional - para mejorar linealidad)
# Aplicamos log transform para manejar la asimetría en 'charges'
y_log = np.log1p(y)  # log(1 + y) para evitar problemas con ceros

# 5. DIVISIÓN DE DATOS
X_train, X_test, y_train, y_test = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

print(f"\n=== DIVISIÓN DE DATOS ===")
print(f"Entrenamiento: {X_train.shape[0]} muestras")
print(f"Prueba: {X_test.shape[0]} muestras")

# 6. ESCALADO DE CARACTERÍSTICAS
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"\n=== ESCALADO COMPLETADO ===")
print(f"Media después del escalado: {np.mean(X_train_scaled, axis=0)}")
print(f"Desviación estándar después del escalado: {np.std(X_train_scaled, axis=0)}")

# 7. ENTRENAMIENTO DEL MODELO DE REGRESIÓN LINEAL
print("\n=== ENTRENAMIENTO DEL MODELO ===")
model = LinearRegression()
model.fit(X_train_scaled, y_train)

print("Modelo entrenado exitosamente!")
print(f"Coeficientes: {model.coef_}")
print(f"Intercepto: {model.intercept_}")

# 8. PREDICCIONES Y EVALUACIÓN
y_pred_log = model.predict(X_test_scaled)

# Convertir predicciones de vuelta a la escala original
y_pred = np.expm1(y_pred_log)
y_test_original = np.expm1(y_test)

# Métricas de evaluación
mse = mean_squared_error(y_test_original, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test_original, y_pred)
r2 = r2_score(y_test_original, y_pred)

print(f"\n=== EVALUACIÓN DEL MODELO ===")
print(f"Error Cuadrático Medio (MSE): {mse:.2f}")
print(f"Raíz del Error Cuadrático Medio (RMSE): {rmse:.2f}")
print(f"Error Absoluto Medio (MAE): {mae:.2f}")
print(f"Coeficiente de Determinación (R²): {r2:.4f}")

# 9. ANÁLISIS DE RESIDUOS
residuals = y_test_original - y_pred

plt.figure(figsize=(15, 5))

# Gráfico de residuos vs predicciones
plt.subplot(1, 3, 1)
plt.scatter(y_pred, residuals, alpha=0.6)
plt.axhline(y=0, color='red', linestyle='--')
plt.xlabel('Predicciones')
plt.ylabel('Residuos')
plt.title('Residuos vs Predicciones')

# Histograma de residuos
plt.subplot(1, 3, 2)
sns.histplot(residuals, kde=True)
plt.xlabel('Residuos')
plt.title('Distribución de Residuos')

# Gráfico Q-Q para normalidad de residuos
plt.subplot(1, 3, 3)
from scipy import stats
stats.probplot(residuals, dist="norm", plot=plt)
plt.title('Gráfico Q-Q de Residuos')

plt.tight_layout()
plt.show()

# 10. IMPORTANCIA DE CARACTERÍSTICAS
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'coefficient': model.coef_,
    'abs_coefficient': np.abs(model.coef_)
}).sort_values('abs_coefficient', ascending=False)

print(f"\n=== IMPORTANCIA DE CARACTERÍSTICAS ===")
print(feature_importance)

# 11. PREDICCIÓN DE EJEMPLO
print(f"\n=== PREDICCIÓN DE EJEMPLO ===")
sample_idx = 0
sample_features = X_test.iloc[sample_idx:sample_idx+1]
sample_actual = y_test_original.iloc[sample_idx]

# Preprocesar la muestra de la misma manera
sample_scaled = scaler.transform(sample_features)
sample_pred_log = model.predict(sample_scaled)
sample_pred = np.expm1(sample_pred_log)[0]

print(f"Características de ejemplo:")
for col in sample_features.columns:
    print(f"  {col}: {sample_features[col].values[0]}")
print(f"\nCosto médico real: ${sample_actual:.2f}")
print(f"Costo médico predicho: ${sample_pred:.2f}")
print(f"Error: ${abs(sample_actual - sample_pred):.2f}")

# 12. ANÁLISIS ADICIONAL: EFECTO DE FUMADOR
print(f"\n=== ANÁLISIS POR FUMADOR ===")
smoker_effect = model.coef_[list(X.columns).index('smoker')]
print(f"Coeficiente para 'smoker': {smoker_effect:.4f}")
print("Interpretación: Ser fumador aumenta significativamente los costos médicos")

# 13. GUARDAR EL MODELO (opcional)
import joblib
model_data = {
    'model': model,
    'scaler': scaler,
    'label_encoders': label_encoders,
    'feature_names': list(X.columns)
}

joblib.dump(model_data, 'insurance_linear_regression_model.pkl')
print(f"\nModelo guardado como 'insurance_linear_regression_model.pkl'")